#ifndef __LIBKWS_BYLE_H__
#define __LIBKWS_BYLE_H__
#include "byle_kwsA_SDK_lib.h"


#define BYLE_ASR_TIMEOUT           UNI_ASR_TIMEOUT   


static const u16 Byle_kws_msg_table[]=
{ 
  KEY_NULL,
  TURNON_LED,
	CABINET_LED_ON,
	WARDROBE_LED_ON,
	SHOE_CABINET_LED_ON,
	WINE_CABINET_LED_ON,
	TURNOFF_LED,
	CABINET_LED_OFF,
	WARDROBE_LED_OFF,
	SHOE_CABINET_LED_OFF,
	WINE_CABINET_LED_OFF,
	LIGHT_UP_LED,
	CABINET_LED_UP,
	WARDROBE_LED_UP,
	SHOE_CABINET_LED_UP,
	WINE_CABINET_LED_UP,
	LIGHT_DOWN_LED,
	CABINET_LED_DOWN,
	WARDROBE_LED_DOWN,
	SHOE_CABINET_LED_DOWN,
	WINE_CABINET_LED_DOWN, //  eCMD_wakeup_uni,  可以把每个消息对应词条顺序下来
	SLEEP_MODE_LED,
	DELAY_MODE_LED,
	SHOW_MODE_LED,
	LOW_POWER_MODE_LED,
	SET_LIGHT_LED,
	SET_NORMAL_MODE_LED,
	SET_CABINET_LED,
	SET_WARDROBE_LED,
	SET_SHOE_CABINET_LED,
	SET_WINE_CABINET_LED,

};


#endif
