/**************************************************************************
 * Copyright (C) 2021-2023  byle
 *
 * byle z MODIFY.
 *
 * This file was generated by byle_res_build_tool.py v1.2
 *
 **************************************************************************/
#ifndef __BYLE_CUST_CONFIG_H__
#define __BYLE_CUST_CONFIG_H__

#define kwsappKey "b0ad71e8b3b542d5abb23eac69df1a05d9c253ac"

#define kwsappSecret "f5dd89c9cd6345149f5db99781fa7070"

#define kwsversion "1.0.0"

#define kwsappType "hb_new_us325_lib-offline"

#define Kws_Lib_language  "cn"

#define Kws_Lib_size   SIZE_M1

#define BYLE_ASR_TONE_VOL           50//0--100%
#define BYLE_ASR_TIMEOUT           15    //ASR timeout Xs

#define MIC_ARRY_TYPE_LINER   0
#define MIC_ARRY_TYPE_CIRCLE  1
#define ACOUSTIC_MODEL_FIELD_NEAR 0
#define ACOUSTIC_MODEL_FIELD_FAR  1

#define KWS_WAKEUP_SCORE_THRED    (-0.55)
#define KWS_SLEEP_SCORE_THRED    (0.44)
#ifndef KWS_CMD_SCORE_THRED         //BZ
#define KWS_CMD_SCORE_THRED       (-0.41)
#endif       //BZ
#define KWS_HASHTABLE_SIZE        (0)

/*---MIC config---*/
#define ACOUSTIC_MODEL_FIELD  ACOUSTIC_MODEL_FIELD_FAR
#define BYLE_MIC_ARRY_NUM          1

#define LOCAL_TONE_MAX_VOLUME      "101"
#define LOCAL_TONE_MIN_VOLUME      "102"
#define DEFAULT_PCM_WAKEUP        "103"
//#define DEFAULT_PCM_ASR_TIMEOUT   "104"
#define DEFAULT_PCM_WELCOME       "105"
#define  KWSA_SDK_POWER_ON_TONE  DEFAULT_PCM_WELCOME

typedef struct {
  unsigned int  key_word_hash_code; /* 存放识别词汇对应的hashcode */
  unsigned char nlu_content_str_index; /* 存放nlu映射表中的索引，实现多个识别词汇可对应同一个nlu，暂支持256条，如果不够换u16 */
  char          *hash_collision_orginal_str; /* 类似Java String equal，当hash发生碰撞时，赋值为识别词汇，否则设置为NULL */
} uni_nlu_content_mapping_t;

// cmd match cnt==36
#define Kws_Lib_Type         KwsA_Light_Ac_Fan_K3_LIB
enum {
  eCMD_wakeup_uni,
  eCMD_default_open,
  eCMD_default_close,
  eCMD_brightthelight,
  eCMD_dimthelight,
  eCMD_changecolor,
  eCMD_musicmode,
  eCMD_ColorfulMode,
  eCMD_white,
  eCMD_red,
  eCMD_orange,
  eCMD_yellow,
  eCMD_green,
  eCMD_cyan,
  eCMD_blue,
  eCMD_purple,
  eCMD_BRAND_DEFAULT,
  eCMD_ACTION_CLOSE,
  eCMD_ACTION_OPEN,
  eCMD_MODE_AUTO,
  eCMD_MODE_COOL,
  eCMD_MODE_CHUSHI,
  eCMD_MODE_TONGF,
  eCMD_MODE_HOT,
  eCMD_ACTION_TEMP_16,
  eCMD_ACTION_TEMP_17,
  eCMD_ACTION_TEMP_18,
  eCMD_ACTION_TEMP_19,
  eCMD_ACTION_TEMP_20,
  eCMD_ACTION_TEMP_21,
  eCMD_ACTION_TEMP_22,
  eCMD_ACTION_TEMP_23,
  eCMD_ACTION_TEMP_24,
  eCMD_ACTION_TEMP_25,
  eCMD_ACTION_TEMP_26,
  eCMD_ACTION_TEMP_27,
  eCMD_ACTION_TEMP_28,
  eCMD_ACTION_TEMP_29,
  eCMD_ACTION_TEMP_30,
  eCMD_WIND_AUTO,
  eCMD_WIND_MIN,
  eCMD_WIND_MID,
  eCMD_WIND_MAX,
  eCMD_WIND_UD_AUTO,
  eCMD_WIND_UD_STOP,
  eCMD_WIND_LR_AUTO,
  eCMD_WIND_LR_STOP,
  eCMD_WIND_UDLR_AUTO,
  eCMD_WIND_UDLR_STOP,
  eCMD_TIME_1H,
  eCMD_TIME_2H,
  eCMD_TIME_3H,
  eCMD_TIME_4H,
  eCMD_TIME_5H,
  eCMD_TIME_6H,
  eCMD_TIME_7H,
  eCMD_TIME_8H,
  eCMD_TIME_CANCEL,
  eCMD_BRAND_SET,
  eCMD_BRAND_MATCH,
  eCMD_BRAND_MATCH_ST,
  eCMD_BRAND_AUX,
  eCMD_BRAND_ZHIGAO,
  eCMD_BRAND_SONGXIA,
  eCMD_BRAND_GREE,
  eCMD_BRAND_HAIXIN,
  eCMD_BRAND_HAIER,
  eCMD_BRAND_KELON,
  eCMD_BRAND_MIDEA,
  eCMD_BRAND_CHANGHONG,
  eCMD_BRAND_RILI,
  eCMD_BRAND_DAJIN,
  eCMD_BRAND_XIAOMI,
  eCMD_BRAND_SANSUNG,
  eCMD_BRAND_XTE,
  eCMD_BRAND_KANGJIA,
  eCMD_BRAND_GELANSHI,
  eCMD_BRAND_CHUANGWEI,
  eCMD_BRAND_DONGZHI,
  eCMD_BRAND_LG,
  eCMD_BRAND_TCL,
  eCMD_BRAND_XINFEI,
  eCMD_BRAND_SANLING,
  eCMD_BRAND_XIAPU,
  eCMD_BRAND_HUIERPU,
  eCMD_BRAND_LEJIN,
  eCMD_BRAND_XINKE,
  eCMD_BRAND_CHUNLAN,
  eCMD_BRAND_YANGZI,
  eCMD_BRAND_AOKEMA,
  eCMD_BRAND_FUSHITONG,
  eCMD_BRAND_SEARCH,
  eCMD_BRAND_SEARCH_STOP,
  eCMD_NEXT_REMOTE,



    eCMD_cmd_no,
//  eCMD_WIND_MID,
  eCMD_WIND_JZ,
  eCMD_BRAND_LG1,
  eCMD_BRAND_TCL1,//	77
  eCMD_BRAND_TCL2,//	78
  eCMD_BRAND_TCL3,//	 79
  eCMD_BRAND_TCL4,//80
  eCMD_BRAND_FEILIPU,
//  eCMD_BRAND_SEARCH,//	 37   搜索空调
//  eCMD_BRAND_SEARCH_STOP,//    38 停止搜索
//  eCMD_WIND_UDLR_AUTO,
//  eCMD_WIND_UDLR_STOP,
  eCMD_BRAND_HUALING,
  eCMD_BRAND_SANLINGDIANJI,
//  eCMD_BRAND_SANLING,
 // eCMD_BRAND_YANGZI,
  eCMD_BRAND_YORK,
  eCMD_BRAND_CHANGLING,
  eCMD_BRAND_LESHENG,
  eCMD_BRAND_YUETU,
 // eCMD_BRAND_XINKE,
  eCMD_BRAND_NEITIAN,
  eCMD_BRAND_MAIKEWEIER,
  eCMD_BRAND_HUABAO,
  eCMD_BRAND_SANYANG,
  eCMD_BRAND_YINGHUA,
 // eCMD_BRAND_XINFEI,
  eCMD_BRAND_SHAP,
 // eCMD_BRAND_HUIERPU,
 // eCMD_BRAND_CHUNLAN,

};

#define NLU_CONTENT_MAP_SIZE 96
#define NLU_CONTENT_SIZE 94
extern const char* g_nlu_content_str[NLU_CONTENT_SIZE][2];
extern const uni_nlu_content_mapping_t g_nlu_content_mapping[NLU_CONTENT_MAP_SIZE];
/*web填写词条：{
wakeup_uni=小艾小艾@我在
default_open=打开夜灯@打开夜灯
default_close=关闭夜灯@关闭夜灯
brightthelight=夜灯调亮@夜灯调亮
dimthelight=夜灯调暗@夜灯调暗
changecolor=夜灯变色@夜灯变色
musicmode=音乐模式@音乐模式
ColorfulMode=七彩模式@七彩模式
white=白色@白色
red=红色@红色
orange=橙色@橙色
yellow=黄色@黄色
green=绿色@绿色
cyan=青色@青色
blue=蓝色@蓝色
purple=紫色@紫色
BRAND_DEFAULT=恢复出厂设置@已恢复出厂设置
ACTION_CLOSE=关闭空调@空调已关闭
ACTION_OPEN=打开空调@空调已打开
MODE_AUTO=自动模式@自动模式
MODE_COOL=制冷模式@制冷模式
MODE_CHUSHI=除湿模式@除湿模式
MODE_TONGF=送风模式@送风模式
MODE_HOT=加热模式|制热模式@加热模式|制热模式
ACTION_TEMP_16=十六度@十六度
ACTION_TEMP_17=十七度@十七度
ACTION_TEMP_18=十八度@十八度
ACTION_TEMP_19=十九度@十九度
ACTION_TEMP_20=二十度@二十度
ACTION_TEMP_21=二十一度@二十一度
ACTION_TEMP_22=二十二度@二十二度
ACTION_TEMP_23=二十三度@二十三度
ACTION_TEMP_24=二十四度@二十四度
ACTION_TEMP_25=二十五度@二十五度
ACTION_TEMP_26=二十六度@二十六度
ACTION_TEMP_27=二十七度@二十七度
ACTION_TEMP_28=二十八度@二十八度
ACTION_TEMP_29=二十九度@二十九度
ACTION_TEMP_30=三十度@三十度
WIND_AUTO=自动风速@自动风速
WIND_MIN=最小风速@最小风速
WIND_MID=中等风速@中等风速
WIND_MAX=最大风速@最大风速
WIND_UD_AUTO=打开上下扫风@已打开上下扫风
WIND_UD_STOP=关闭上下扫风@已停止上下扫风
WIND_LR_AUTO=打开左右扫风@已打开左右扫风
WIND_LR_STOP=关闭左右扫风@已停止左右扫风
WIND_UDLR_AUTO=打开扫风@打开扫风
WIND_UDLR_STOP=关闭扫风@关闭扫风
TIME_1H=定时一小时@已定时一小时
TIME_2H=定时二小时|定时两小时@已定时二小时|已定时两小时
TIME_3H=定时三小时@已定时三小时
TIME_4H=定时四小时@已定时四小时
TIME_5H=定时五小时@已定时五小时
TIME_6H=定时六小时@已定时六小时
TIME_7H=定时七小时@已定时七小时
TIME_8H=定时八小时@已定时八小时
TIME_CANCEL=取消定时@已取消定时
BRAND_SET=设置空调品牌@请对我说出空调品牌,例如格力空调
BRAND_MATCH=匹配空调@请拿起空调遥控器对准我，按下开关键
BRAND_MATCH_ST=退出匹配@已退出匹配
BRAND_AUX=奥克斯空调@好的，如不能使用，请进行匹配空调
BRAND_ZHIGAO=志高空调@好的，如不能使用，请进行匹配空调
BRAND_SONGXIA=松下空调@好的，如不能使用，请进行匹配空调
BRAND_GREE=格力空调@好的，如不能使用，请进行匹配空调
BRAND_HAIXIN=海信空调@好的，如不能使用，请进行匹配空调
BRAND_HAIER=海尔空调@好的，如不能使用，请进行匹配空调
BRAND_KELON=科龙空调@好的，如不能使用，请进行匹配空调
BRAND_MIDEA=美的空调@好的，如不能使用，请进行匹配空调
BRAND_CHANGHONG=长虹空调@好的，如不能使用，请进行匹配空调
BRAND_RILI=日立空调@好的，如不能使用，请进行匹配空调
BRAND_DAJIN=大金空调@好的，如不能使用，请进行匹配空调
BRAND_XIAOMI=小米空调@好的，如不能使用，请进行匹配空调
BRAND_SANSUNG=三星空调@好的，如不能使用，请进行匹配空调
BRAND_XTE=小天鹅空调@好的，如不能使用，请进行匹配空调
BRAND_KANGJIA=康佳空调@好的，如不能使用，请进行匹配空调
BRAND_GELANSHI=格兰仕空调@好的，如不能使用，请进行匹配空调
BRAND_CHUANGWEI=创维空调@好的，如不能使用，请进行匹配空调
BRAND_DONGZHI=东芝空调@好的，如不能使用，请进行匹配空调
BRAND_LG=l g 空调@好的，如不能使用，请进行匹配空调
BRAND_TCL=t c l 空调@好的，如不能使用，请进行匹配空调
BRAND_XINFEI=新飞空调@好的，如不能使用，请进行匹配空调
BRAND_SANLING=三菱空调@好的，如不能使用，请进行匹配空调
BRAND_XIAPU=夏普空调@好的，如不能使用，请进行匹配空调
BRAND_HUIERPU=惠而浦空调@好的，如不能使用，请进行匹配空调
BRAND_LEJIN=乐金空调@好的，如不能使用，请进行匹配空调
BRAND_XINKE=新科空调@好的，如不能使用，请进行匹配空调
BRAND_CHUNLAN=春兰空调@好的，如不能使用，请进行匹配空调
BRAND_YANGZI=扬子空调@好的，如不能使用，请进行匹配空调
BRAND_AOKEMA=澳柯玛空调@好的，如不能使用，请进行匹配空调
BRAND_FUSHITONG=富士通空调@好的，如不能使用，请进行匹配空调
BRAND_SEARCH=搜索空调@搜索空调
BRAND_SEARCH_STOP=停止搜索@停止搜索
NEXT_REMOTE=下一套遥控码@下一套遥控码
}*/
#ifdef APP_CHANGE_WAKEUP_CMD_EN
#define WAKE_UP_NUM 1
static const  char*  updata_wakeup_name[]= {
"小艾小艾",
};

#define KWS_CMD_NUM 95
static const  char*  updata_cmd_name[]= {
"打开夜灯",
"关闭夜灯",
"夜灯调亮",
"夜灯调暗",
"夜灯变色",
"音乐模式",
"七彩模式",
"白色",
"红色",
"橙色",
"黄色",
"绿色",
"青色",
"蓝色",
"紫色",
"恢复出厂设置",
"关闭空调",
"打开空调",
"自动模式",
"制冷模式",
"除湿模式",
"送风模式",
"加热模式",
"制热模式",
"十六度",
"十七度",
"十八度",
"十九度",
"二十度",
"二十一度",
"二十二度",
"二十三度",
"二十四度",
"二十五度",
"二十六度",
"二十七度",
"二十八度",
"二十九度",
"三十度",
"自动风速",
"最小风速",
"中等风速",
"最大风速",
"打开上下扫风",
"关闭上下扫风",
"打开左右扫风",
"关闭左右扫风",
"打开扫风",
"关闭扫风",
"定时一小时",
"定时二小时",
"定时两小时",
"定时三小时",
"定时四小时",
"定时五小时",
"定时六小时",
"定时七小时",
"定时八小时",
"取消定时",
"设置空调品牌",
"匹配空调",
"退出匹配",
"奥克斯空调",
"志高空调",
"松下空调",
"格力空调",
"海信空调",
"海尔空调",
"科龙空调",
"美的空调",
"长虹空调",
"日立空调",
"大金空调",
"小米空调",
"三星空调",
"小天鹅空调",
"康佳空调",
"格兰仕空调",
"创维空调",
"东芝空调",
"l g 空调",
"t c l 空调",
"新飞空调",
"三菱空调",
"夏普空调",
"惠而浦空调",
"乐金空调",
"新科空调",
"春兰空调",
"扬子空调",
"澳柯玛空调",
"富士通空调",
"搜索空调",
"停止搜索",
"下一套遥控码",
};
#endif
static const char* g_nlu_content_str_byle[][2] = {
  [eCMD_wakeup_uni] = {"wakeup_uni", "103"},
  [eCMD_default_open] = {"default_open", "106"},
  [eCMD_default_close] = {"default_close", "107"},
  [eCMD_brightthelight] = {"brightthelight", "108"},
  [eCMD_dimthelight] = {"dimthelight", "109"},
  [eCMD_changecolor] = {"changecolor", "110"},
  [eCMD_musicmode] = {"musicmode", "111"},
  [eCMD_ColorfulMode] = {"ColorfulMode", "112"},
  [eCMD_white] = {"white", "113"},
  [eCMD_red] = {"red", "114"},
  [eCMD_orange] = {"orange", "115"},
  [eCMD_yellow] = {"yellow", "116"},
  [eCMD_green] = {"green", "117"},
  [eCMD_cyan] = {"cyan", "118"},
  [eCMD_blue] = {"blue", "119"},
  [eCMD_purple] = {"purple", "120"},
  [eCMD_BRAND_DEFAULT] = {"BRAND_DEFAULT", "121"},
  [eCMD_ACTION_CLOSE] = {"ACTION_CLOSE", "122"},
  [eCMD_ACTION_OPEN] = {"ACTION_OPEN", "123"},
  [eCMD_MODE_AUTO] = {"MODE_AUTO", "124"},
  [eCMD_MODE_COOL] = {"MODE_COOL", "125"},
  [eCMD_MODE_CHUSHI] = {"MODE_CHUSHI", "126"},
  [eCMD_MODE_TONGF] = {"MODE_TONGF", "127"},
  [eCMD_MODE_HOT] = {"MODE_HOT", "128, 129"},
  [eCMD_ACTION_TEMP_16] = {"ACTION_TEMP_16", "130"},
  [eCMD_ACTION_TEMP_17] = {"ACTION_TEMP_17", "131"},
  [eCMD_ACTION_TEMP_18] = {"ACTION_TEMP_18", "132"},
  [eCMD_ACTION_TEMP_19] = {"ACTION_TEMP_19", "133"},
  [eCMD_ACTION_TEMP_20] = {"ACTION_TEMP_20", "134"},
  [eCMD_ACTION_TEMP_21] = {"ACTION_TEMP_21", "135"},
  [eCMD_ACTION_TEMP_22] = {"ACTION_TEMP_22", "136"},
  [eCMD_ACTION_TEMP_23] = {"ACTION_TEMP_23", "137"},
  [eCMD_ACTION_TEMP_24] = {"ACTION_TEMP_24", "138"},
  [eCMD_ACTION_TEMP_25] = {"ACTION_TEMP_25", "139"},
  [eCMD_ACTION_TEMP_26] = {"ACTION_TEMP_26", "140"},
  [eCMD_ACTION_TEMP_27] = {"ACTION_TEMP_27", "141"},
  [eCMD_ACTION_TEMP_28] = {"ACTION_TEMP_28", "142"},
  [eCMD_ACTION_TEMP_29] = {"ACTION_TEMP_29", "143"},
  [eCMD_ACTION_TEMP_30] = {"ACTION_TEMP_30", "144"},
  [eCMD_WIND_AUTO] = {"WIND_AUTO", "145"},
  [eCMD_WIND_MIN] = {"WIND_MIN", "146"},
  [eCMD_WIND_MID] = {"WIND_MID", "147"},
  [eCMD_WIND_MAX] = {"WIND_MAX", "148"},
  [eCMD_WIND_UD_AUTO] = {"WIND_UD_AUTO", "149"},
  [eCMD_WIND_UD_STOP] = {"WIND_UD_STOP", "150"},
  [eCMD_WIND_LR_AUTO] = {"WIND_LR_AUTO", "151"},
  [eCMD_WIND_LR_STOP] = {"WIND_LR_STOP", "152"},
  [eCMD_WIND_UDLR_AUTO] = {"WIND_UDLR_AUTO", "153"},
  [eCMD_WIND_UDLR_STOP] = {"WIND_UDLR_STOP", "154"},
  [eCMD_TIME_1H] = {"TIME_1H", "155"},
  [eCMD_TIME_2H] = {"TIME_2H", "156, 157"},
  [eCMD_TIME_3H] = {"TIME_3H", "158"},
  [eCMD_TIME_4H] = {"TIME_4H", "159"},
  [eCMD_TIME_5H] = {"TIME_5H", "160"},
  [eCMD_TIME_6H] = {"TIME_6H", "161"},
  [eCMD_TIME_7H] = {"TIME_7H", "162"},
  [eCMD_TIME_8H] = {"TIME_8H", "163"},
  [eCMD_TIME_CANCEL] = {"TIME_CANCEL", "164"},
  [eCMD_BRAND_SET] = {"BRAND_SET", "165"},
  [eCMD_BRAND_MATCH] = {"BRAND_MATCH", "166"},
  [eCMD_BRAND_MATCH_ST] = {"BRAND_MATCH_ST", "167"},
  [eCMD_BRAND_AUX] = {"BRAND_AUX", "168"},
  [eCMD_BRAND_ZHIGAO] = {"BRAND_ZHIGAO", "168"},
  [eCMD_BRAND_SONGXIA] = {"BRAND_SONGXIA", "168"},
  [eCMD_BRAND_GREE] = {"BRAND_GREE", "168"},
  [eCMD_BRAND_HAIXIN] = {"BRAND_HAIXIN", "168"},
  [eCMD_BRAND_HAIER] = {"BRAND_HAIER", "168"},
  [eCMD_BRAND_KELON] = {"BRAND_KELON", "168"},
  [eCMD_BRAND_MIDEA] = {"BRAND_MIDEA", "168"},
  [eCMD_BRAND_CHANGHONG] = {"BRAND_CHANGHONG", "168"},
  [eCMD_BRAND_RILI] = {"BRAND_RILI", "168"},
  [eCMD_BRAND_DAJIN] = {"BRAND_DAJIN", "168"},
  [eCMD_BRAND_XIAOMI] = {"BRAND_XIAOMI", "168"},
  [eCMD_BRAND_SANSUNG] = {"BRAND_SANSUNG", "168"},
  [eCMD_BRAND_XTE] = {"BRAND_XTE", "168"},
  [eCMD_BRAND_KANGJIA] = {"BRAND_KANGJIA", "168"},
  [eCMD_BRAND_GELANSHI] = {"BRAND_GELANSHI", "168"},
  [eCMD_BRAND_CHUANGWEI] = {"BRAND_CHUANGWEI", "168"},
  [eCMD_BRAND_DONGZHI] = {"BRAND_DONGZHI", "168"},
  [eCMD_BRAND_LG] = {"BRAND_LG", "168"},
  [eCMD_BRAND_TCL] = {"BRAND_TCL", "168"},
  [eCMD_BRAND_XINFEI] = {"BRAND_XINFEI", "168"},
  [eCMD_BRAND_SANLING] = {"BRAND_SANLING", "168"},
  [eCMD_BRAND_XIAPU] = {"BRAND_XIAPU", "168"},
  [eCMD_BRAND_HUIERPU] = {"BRAND_HUIERPU", "168"},
  [eCMD_BRAND_LEJIN] = {"BRAND_LEJIN", "168"},
  [eCMD_BRAND_XINKE] = {"BRAND_XINKE", "168"},
  [eCMD_BRAND_CHUNLAN] = {"BRAND_CHUNLAN", "168"},
  [eCMD_BRAND_YANGZI] = {"BRAND_YANGZI", "168"},
  [eCMD_BRAND_AOKEMA] = {"BRAND_AOKEMA", "168"},
  [eCMD_BRAND_FUSHITONG] = {"BRAND_FUSHITONG", "168"},
  [eCMD_BRAND_SEARCH] = {"BRAND_SEARCH", "169"},
  [eCMD_BRAND_SEARCH_STOP] = {"BRAND_SEARCH_STOP", "170"},
  [eCMD_NEXT_REMOTE] = {"NEXT_REMOTE", "171"},
};

/*TODO perf sort by hashcode O(logN), now version O(N)*/
static const uni_nlu_content_mapping_t g_nlu_content_mapping_byle[] = {
  {2102002098U/*小艾小艾*/, eCMD_wakeup_uni, NULL},
  {3421717457U/*打开夜灯*/, eCMD_default_open, NULL},
  {2480644484U/*关闭夜灯*/, eCMD_default_close, NULL},
  {43654325U/*夜灯调亮*/, eCMD_brightthelight, NULL},
  {43655232U/*夜灯调暗*/, eCMD_dimthelight, NULL},
  {4222885915U/*夜灯变色*/, eCMD_changecolor, NULL},
  {3158896343U/*音乐模式*/, eCMD_musicmode, NULL},
  {2963660507U/*七彩模式*/, eCMD_ColorfulMode, NULL},
  {2465523174U/*白色*/, eCMD_white, NULL},
  {2495195010U/*红色*/, eCMD_red, NULL},
  {2450597883U/*橙色*/, eCMD_orange, NULL},
  {2552483103U/*黄色*/, eCMD_yellow, NULL},
  {2496982470U/*绿色*/, eCMD_green, NULL},
  {2525194547U/*青色*/, eCMD_cyan, NULL},
  {2487657887U/*蓝色*/, eCMD_blue, NULL},
  {2489922003U/*紫色*/, eCMD_purple, NULL},
  {121111656U/*恢复出厂设置*/, eCMD_BRAND_DEFAULT, NULL},
  {2543416495U/*关闭空调*/, eCMD_ACTION_CLOSE, NULL},
  {3484489468U/*打开空调*/, eCMD_ACTION_OPEN, NULL},
  {2685685105U/*自动模式*/, eCMD_MODE_AUTO, NULL},
  {189670108U/*制冷模式*/, eCMD_MODE_COOL, NULL},
  {3446463601U/*除湿模式*/, eCMD_MODE_CHUSHI, NULL},
  {2356087491U/*送风模式*/, eCMD_MODE_TONGF, NULL},
  {380556943U/*加热模式*/, eCMD_MODE_HOT, NULL},
  {3946129847U/*制热模式*/, eCMD_MODE_HOT, NULL},
  {246084029U/*十六度*/, eCMD_ACTION_TEMP_16, NULL},
  {263303227U/*十七度*/, eCMD_ACTION_TEMP_17, NULL},
  {246024447U/*十八度*/, eCMD_ACTION_TEMP_18, NULL},
  {265001314U/*十九度*/, eCMD_ACTION_TEMP_19, NULL},
  {54308206U/*二十度*/, eCMD_ACTION_TEMP_20, NULL},
  {2956679400U/*二十一度*/, eCMD_ACTION_TEMP_21, NULL},
  {2958883934U/*二十二度*/, eCMD_ACTION_TEMP_22, NULL},
  {2956947519U/*二十三度*/, eCMD_ACTION_TEMP_23, NULL},
  {2959330799U/*二十四度*/, eCMD_ACTION_TEMP_24, NULL},
  {2959122262U/*二十五度*/, eCMD_ACTION_TEMP_25, NULL},
  {2939549575U/*二十六度*/, eCMD_ACTION_TEMP_26, NULL},
  {2956768773U/*二十七度*/, eCMD_ACTION_TEMP_27, NULL},
  {2939489993U/*二十八度*/, eCMD_ACTION_TEMP_28, NULL},
  {2958466860U/*二十九度*/, eCMD_ACTION_TEMP_29, NULL},
  {2496111085U/*三十度*/, eCMD_ACTION_TEMP_30, NULL},
  {2766390924U/*自动风速*/, eCMD_WIND_AUTO, NULL},
  {4180112974U/*最小风速*/, eCMD_WIND_MIN, NULL},
  {3610283774U/*中等风速*/, eCMD_WIND_MID, NULL},
  {271510002U/*最大风速*/, eCMD_WIND_MAX, NULL},
  {1555509158U/*打开上下扫风*/, eCMD_WIND_UD_AUTO, NULL},
  {924924697U/*关闭上下扫风*/, eCMD_WIND_UD_STOP, NULL},
  {3166307098U/*打开左右扫风*/, eCMD_WIND_LR_AUTO, NULL},
  {2535722637U/*关闭左右扫风*/, eCMD_WIND_LR_STOP, NULL},
  {3425861349U/*打开扫风*/, eCMD_WIND_UDLR_AUTO, NULL},
  {2484788376U/*关闭扫风*/, eCMD_WIND_UDLR_STOP, NULL},
  {2217774873U/*定时一小时*/, eCMD_TIME_1H, NULL},
  {3468537827U/*定时二小时*/, eCMD_TIME_2H, NULL},
  {4103136317U/*定时两小时*/, eCMD_TIME_2H, NULL},
  {1615373410U/*定时三小时*/, eCMD_TIME_3H, NULL},
  {3896191154U/*定时四小时*/, eCMD_TIME_4H, NULL},
  {1978632683U/*定时五小时*/, eCMD_TIME_5H, NULL},
  {3004266522U/*定时六小时*/, eCMD_TIME_6H, NULL},
  {585318620U/*定时七小时*/, eCMD_TIME_7H, NULL},
  {1229259160U/*定时八小时*/, eCMD_TIME_8H, NULL},
  {3946143584U/*取消定时*/, eCMD_TIME_CANCEL, NULL},
  {2014785434U/*设置空调品牌*/, eCMD_BRAND_SET, NULL},
  {2029416162U/*匹配空调*/, eCMD_BRAND_MATCH, NULL},
  {4275088110U/*退出匹配*/, eCMD_BRAND_MATCH_ST, NULL},
  {1625945404U/*奥克斯空调*/, eCMD_BRAND_AUX, NULL},
  {1645623836U/*志高空调*/, eCMD_BRAND_ZHIGAO, NULL},
  {2348840851U/*松下空调*/, eCMD_BRAND_SONGXIA, NULL},
  {2588786839U/*格力空调*/, eCMD_BRAND_GREE, NULL},
  {912290689U/*海信空调*/, eCMD_BRAND_HAIXIN, NULL},
  {79839012U/*海尔空调*/, eCMD_BRAND_HAIER, NULL},
  {2901191638U/*科龙空调*/, eCMD_BRAND_KELON, NULL},
  {361127453U/*美的空调*/, eCMD_BRAND_MIDEA, NULL},
  {778384760U/*长虹空调*/, eCMD_BRAND_CHANGHONG, NULL},
  {2849390774U/*日立空调*/, eCMD_BRAND_RILI, NULL},
  {3835200398U/*大金空调*/, eCMD_BRAND_DAJIN, NULL},
  {3781863144U/*小米空调*/, eCMD_BRAND_XIAOMI, NULL},
  {3957817083U/*三星空调*/, eCMD_BRAND_SANSUNG, NULL},
  {2169286098U/*小天鹅空调*/, eCMD_BRAND_XTE, NULL},
  {4287896763U/*康佳空调*/, eCMD_BRAND_KANGJIA, NULL},
  {2306078739U/*格兰仕空调*/, eCMD_BRAND_GELANSHI, NULL},
  {1423049259U/*创维空调*/, eCMD_BRAND_CHUANGWEI, NULL},
  {499570582U/*东芝空调*/, eCMD_BRAND_DONGZHI, NULL},
  {2478773360U/*l g 空调*/, eCMD_BRAND_LG, NULL},
  {497369568U/*t c l 空调*/, eCMD_BRAND_TCL, NULL},
  {1789871911U/*新飞空调*/, eCMD_BRAND_XINFEI, NULL},
  {632681400U/*三菱空调*/, eCMD_BRAND_SANLING, NULL},
  {2362603950U/*夏普空调*/, eCMD_BRAND_XIAPU, NULL},
  {3990140169U/*惠而浦空调*/, eCMD_BRAND_HUIERPU, NULL},
  {554720827U/*乐金空调*/, eCMD_BRAND_LEJIN, NULL},
  {838474324U/*新科空调*/, eCMD_BRAND_XINKE, NULL},
  {1342962880U/*春兰空调*/, eCMD_BRAND_CHUNLAN, NULL},
  {3809424898U/*扬子空调*/, eCMD_BRAND_YANGZI, NULL},
  {2299955036U/*澳柯玛空调*/, eCMD_BRAND_AOKEMA, NULL},
  {1565777627U/*富士通空调*/, eCMD_BRAND_FUSHITONG, NULL},
  {1754941958U/*搜索空调*/, eCMD_BRAND_SEARCH, NULL},
  {955430846U/*停止搜索*/, eCMD_BRAND_SEARCH_STOP, NULL},
  {183563604U/*下一套遥控码*/, eCMD_NEXT_REMOTE, NULL},
};



#ifdef BYLE_UATR_ENABLE
/*
byle 默认的通讯协议
1、通信协议数据格式
[header1][header2][ID][CMD][datal][data2][checksum][BCCcheck][end]
header1:A5
header2:FA
ID:产品ID，可以自定义，暂定为 0
CMD:指令号码,语音模块对外发为0x81，语音模块接收为0x85。
data1，data2:指会内容
checksum: header1+header2+ID+CMD+datal+data2的累和
BCCcheck:header1、header2、ID、CMD、datal、data2 的异或校验
unsigned char calculate_xor_checksum( unsigned char* data, size_t length)
{
unsigned char checksum = 0;
for (size_t i = 0; i < length; i++)
{
checksum ^= data[i];
}
return checksum;
}
end:结束字符,在此为FB
2、串口UART1通信:波特率9600 数据位8 无奇偶校验 停止位1


帧头(2byte)	 产品ID(1byte)"	"CMD(1byte)"	"命令词ID(2byte)"	"和校验(1byte)"	"BCC和校验(1byte)"	"帧尾(1byte)"
0xA5      0xFA	        0x00	                   0x81	             0x01  0x00  	                 0x21	                       0xDF	                            0xFB
*/

#define         FRAME_DATA_LEN 9
#define         FRAME_HEAD1             0xA5
#define         FRAME_HEAD2         0xFA
#define         FRAME_ID         0
#define         FRAME_CMD         0x81
#define         FRAME_DATA1      0x01
#define         FRAME_DATA2       0x00
#define         FRAME_CHECK_SUM    0x21
#define         FRAME_BCCcheck    0xDF
#define         FRAME_END              0XFB


#define         FRAME_ID_OFSET    2
#define         CMD_OFSET    3
#define         DATA1_OFSET     4
#define         DATA2_OFSET     5
#define         CHECK_SUM_OFSET     6

#define   KWS_INDEX_CMD         0x81
#define   FAN_APP_UART_CMD 0x84
#define   TONE_UART_CMD 0X85
#define   TONE_ON_OFF_CMD 0X89
#define   VOLUME_UART_CMD 0X86
#define   BYLE_UART_SEND_USER_CMD_TABLE  FRAME_DATA_LEN
//#define   UART_TX_AS_RX_CMD
#define   CMD_WAKEUP_DATA 0X81
#define  SEND_USER_CMD_POWER    NLU_CONTENT_SIZE
#define  SEND_USER_CMD_EXIT         NLU_CONTENT_SIZE+1


static const unsigned char cmd_table[][FRAME_DATA_LEN]={
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x1,0x0,0x21,0xdf,0xFB},//wakeup_uni=小艾小艾@我在
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x2,0x0,0x22,0xdc,0xFB},//default_open=打开夜灯@打开夜灯
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x3,0x0,0x23,0xdd,0xFB},//default_close=关闭夜灯@关闭夜灯
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x4,0x0,0x24,0xda,0xFB},//brightthelight=夜灯调亮@夜灯调亮
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x5,0x0,0x25,0xdb,0xFB},//dimthelight=夜灯调暗@夜灯调暗
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x6,0x0,0x26,0xd8,0xFB},//changecolor=夜灯变色@夜灯变色
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x7,0x0,0x27,0xd9,0xFB},//musicmode=音乐模式@音乐模式
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x8,0x0,0x28,0xd6,0xFB},//ColorfulMode=七彩模式@七彩模式
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x9,0x0,0x29,0xd7,0xFB},//white=白色@白色
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0xa,0x0,0x2a,0xd4,0xFB},//red=红色@红色
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0xb,0x0,0x2b,0xd5,0xFB},//orange=橙色@橙色
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0xc,0x0,0x2c,0xd2,0xFB},//yellow=黄色@黄色
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0xd,0x0,0x2d,0xd3,0xFB},//green=绿色@绿色
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0xe,0x0,0x2e,0xd0,0xFB},//cyan=青色@青色
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0xf,0x0,0x2f,0xd1,0xFB},//blue=蓝色@蓝色
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x10,0x0,0x30,0xce,0xFB},//purple=紫色@紫色
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x11,0x0,0x31,0xcf,0xFB},//BRAND_DEFAULT=恢复出厂设置@已恢复出厂设置
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x12,0x0,0x32,0xcc,0xFB},//ACTION_CLOSE=关闭空调@空调已关闭
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x13,0x0,0x33,0xcd,0xFB},//ACTION_OPEN=打开空调@空调已打开
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x14,0x0,0x34,0xca,0xFB},//MODE_AUTO=自动模式@自动模式
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x15,0x0,0x35,0xcb,0xFB},//MODE_COOL=制冷模式@制冷模式
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x16,0x0,0x36,0xc8,0xFB},//MODE_CHUSHI=除湿模式@除湿模式
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x17,0x0,0x37,0xc9,0xFB},//MODE_TONGF=送风模式@送风模式
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x18,0x0,0x38,0xc6,0xFB},//MODE_HOT=加热模式|制热模式@加热模式|制热模式
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x19,0x0,0x39,0xc7,0xFB},//ACTION_TEMP_16=十六度@十六度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x1a,0x0,0x3a,0xc4,0xFB},//ACTION_TEMP_17=十七度@十七度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x1b,0x0,0x3b,0xc5,0xFB},//ACTION_TEMP_18=十八度@十八度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x1c,0x0,0x3c,0xc2,0xFB},//ACTION_TEMP_19=十九度@十九度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x1d,0x0,0x3d,0xc3,0xFB},//ACTION_TEMP_20=二十度@二十度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x1e,0x0,0x3e,0xc0,0xFB},//ACTION_TEMP_21=二十一度@二十一度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x1f,0x0,0x3f,0xc1,0xFB},//ACTION_TEMP_22=二十二度@二十二度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x20,0x0,0x40,0xfe,0xFB},//ACTION_TEMP_23=二十三度@二十三度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x21,0x0,0x41,0xff,0xFB},//ACTION_TEMP_24=二十四度@二十四度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x22,0x0,0x42,0xfc,0xFB},//ACTION_TEMP_25=二十五度@二十五度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x23,0x0,0x43,0xfd,0xFB},//ACTION_TEMP_26=二十六度@二十六度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x24,0x0,0x44,0xfa,0xFB},//ACTION_TEMP_27=二十七度@二十七度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x25,0x0,0x45,0xfb,0xFB},//ACTION_TEMP_28=二十八度@二十八度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x26,0x0,0x46,0xf8,0xFB},//ACTION_TEMP_29=二十九度@二十九度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x27,0x0,0x47,0xf9,0xFB},//ACTION_TEMP_30=三十度@三十度
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x28,0x0,0x48,0xf6,0xFB},//WIND_AUTO=自动风速@自动风速
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x29,0x0,0x49,0xf7,0xFB},//WIND_MIN=最小风速@最小风速
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x2a,0x0,0x4a,0xf4,0xFB},//WIND_MID=中等风速@中等风速
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x2b,0x0,0x4b,0xf5,0xFB},//WIND_MAX=最大风速@最大风速
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x2c,0x0,0x4c,0xf2,0xFB},//WIND_UD_AUTO=打开上下扫风@已打开上下扫风
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x2d,0x0,0x4d,0xf3,0xFB},//WIND_UD_STOP=关闭上下扫风@已停止上下扫风
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x2e,0x0,0x4e,0xf0,0xFB},//WIND_LR_AUTO=打开左右扫风@已打开左右扫风
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x2f,0x0,0x4f,0xf1,0xFB},//WIND_LR_STOP=关闭左右扫风@已停止左右扫风
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x30,0x0,0x50,0xee,0xFB},//WIND_UDLR_AUTO=打开扫风@打开扫风
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x31,0x0,0x51,0xef,0xFB},//WIND_UDLR_STOP=关闭扫风@关闭扫风
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x32,0x0,0x52,0xec,0xFB},//TIME_1H=定时一小时@已定时一小时
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x33,0x0,0x53,0xed,0xFB},//TIME_2H=定时二小时|定时两小时@已定时二小时|已定时两小时
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x34,0x0,0x54,0xea,0xFB},//TIME_3H=定时三小时@已定时三小时
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x35,0x0,0x55,0xeb,0xFB},//TIME_4H=定时四小时@已定时四小时
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x36,0x0,0x56,0xe8,0xFB},//TIME_5H=定时五小时@已定时五小时
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x37,0x0,0x57,0xe9,0xFB},//TIME_6H=定时六小时@已定时六小时
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x38,0x0,0x58,0xe6,0xFB},//TIME_7H=定时七小时@已定时七小时
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x39,0x0,0x59,0xe7,0xFB},//TIME_8H=定时八小时@已定时八小时
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x3a,0x0,0x5a,0xe4,0xFB},//TIME_CANCEL=取消定时@已取消定时
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x3b,0x0,0x5b,0xe5,0xFB},//BRAND_SET=设置空调品牌@请对我说出空调品牌,例如格力空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x3c,0x0,0x5c,0xe2,0xFB},//BRAND_MATCH=匹配空调@请拿起空调遥控器对准我，按下开关键
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x3d,0x0,0x5d,0xe3,0xFB},//BRAND_MATCH_ST=退出匹配@已退出匹配
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x3e,0x0,0x5e,0xe0,0xFB},//BRAND_AUX=奥克斯空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x3f,0x0,0x5f,0xe1,0xFB},//BRAND_ZHIGAO=志高空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x40,0x0,0x60,0x9e,0xFB},//BRAND_SONGXIA=松下空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x41,0x0,0x61,0x9f,0xFB},//BRAND_GREE=格力空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x42,0x0,0x62,0x9c,0xFB},//BRAND_HAIXIN=海信空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x43,0x0,0x63,0x9d,0xFB},//BRAND_HAIER=海尔空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x44,0x0,0x64,0x9a,0xFB},//BRAND_KELON=科龙空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x45,0x0,0x65,0x9b,0xFB},//BRAND_MIDEA=美的空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x46,0x0,0x66,0x98,0xFB},//BRAND_CHANGHONG=长虹空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x47,0x0,0x67,0x99,0xFB},//BRAND_RILI=日立空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x48,0x0,0x68,0x96,0xFB},//BRAND_DAJIN=大金空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x49,0x0,0x69,0x97,0xFB},//BRAND_XIAOMI=小米空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x4a,0x0,0x6a,0x94,0xFB},//BRAND_SANSUNG=三星空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x4b,0x0,0x6b,0x95,0xFB},//BRAND_XTE=小天鹅空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x4c,0x0,0x6c,0x92,0xFB},//BRAND_KANGJIA=康佳空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x4d,0x0,0x6d,0x93,0xFB},//BRAND_GELANSHI=格兰仕空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x4e,0x0,0x6e,0x90,0xFB},//BRAND_CHUANGWEI=创维空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x4f,0x0,0x6f,0x91,0xFB},//BRAND_DONGZHI=东芝空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x50,0x0,0x70,0x8e,0xFB},//BRAND_LG=l g 空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x51,0x0,0x71,0x8f,0xFB},//BRAND_TCL=t c l 空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x52,0x0,0x72,0x8c,0xFB},//BRAND_XINFEI=新飞空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x53,0x0,0x73,0x8d,0xFB},//BRAND_SANLING=三菱空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x54,0x0,0x74,0x8a,0xFB},//BRAND_XIAPU=夏普空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x55,0x0,0x75,0x8b,0xFB},//BRAND_HUIERPU=惠而浦空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x56,0x0,0x76,0x88,0xFB},//BRAND_LEJIN=乐金空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x57,0x0,0x77,0x89,0xFB},//BRAND_XINKE=新科空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x58,0x0,0x78,0x86,0xFB},//BRAND_CHUNLAN=春兰空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x59,0x0,0x79,0x87,0xFB},//BRAND_YANGZI=扬子空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x5a,0x0,0x7a,0x84,0xFB},//BRAND_AOKEMA=澳柯玛空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x5b,0x0,0x7b,0x85,0xFB},//BRAND_FUSHITONG=富士通空调@好的，如不能使用，请进行匹配空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x5c,0x0,0x7c,0x82,0xFB},//BRAND_SEARCH=搜索空调@搜索空调
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x5d,0x0,0x7d,0x83,0xFB},//BRAND_SEARCH_STOP=停止搜索@停止搜索
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x5e,0x0,0x7e,0x80,0xFB},//NEXT_REMOTE=下一套遥控码@下一套遥控码
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x5f,0x0,0x7f,0x81,0xFB},// poower on  & exit
{FRAME_HEAD1,FRAME_HEAD2,FRAME_ID,KWS_INDEX_CMD,0x60,0x0,0x80,0xbe,0xFB},// poower on  & exit
};
   #ifdef KWS_TONE_PASSIVE_EN
   #define KWS_TONE_PASSIVE_TABLE
   static const unsigned char need_tone_cmd_table[]={
 };
#endif
#endif
enum {
     BYLE_KWS_IDEX_TONE_NUM_101,
     BYLE_KWS_IDEX_TONE_NUM_102,
     BYLE_KWS_IDEX_TONE_NUM_103,
     BYLE_KWS_IDEX_TONE_NUM_104,
     BYLE_KWS_IDEX_TONE_NUM_105,
     BYLE_KWS_IDEX_TONE_NUM_106,
     BYLE_KWS_IDEX_TONE_NUM_107,
     BYLE_KWS_IDEX_TONE_NUM_108,
     BYLE_KWS_IDEX_TONE_NUM_109,
     BYLE_KWS_IDEX_TONE_NUM_110,
     BYLE_KWS_IDEX_TONE_NUM_111,
     BYLE_KWS_IDEX_TONE_NUM_112,
     BYLE_KWS_IDEX_TONE_NUM_113,
     BYLE_KWS_IDEX_TONE_NUM_114,
     BYLE_KWS_IDEX_TONE_NUM_115,
     BYLE_KWS_IDEX_TONE_NUM_116,
     BYLE_KWS_IDEX_TONE_NUM_117,
     BYLE_KWS_IDEX_TONE_NUM_118,
     BYLE_KWS_IDEX_TONE_NUM_119,
     BYLE_KWS_IDEX_TONE_NUM_120,
     BYLE_KWS_IDEX_TONE_NUM_121,
     BYLE_KWS_IDEX_TONE_NUM_122,
     BYLE_KWS_IDEX_TONE_NUM_123,
     BYLE_KWS_IDEX_TONE_NUM_124,
     BYLE_KWS_IDEX_TONE_NUM_125,
     BYLE_KWS_IDEX_TONE_NUM_126,
     BYLE_KWS_IDEX_TONE_NUM_127,
     BYLE_KWS_IDEX_TONE_NUM_128,
     BYLE_KWS_IDEX_TONE_NUM_129,
     BYLE_KWS_IDEX_TONE_NUM_130,
     BYLE_KWS_IDEX_TONE_NUM_131,
     BYLE_KWS_IDEX_TONE_NUM_132,
     BYLE_KWS_IDEX_TONE_NUM_133,
     BYLE_KWS_IDEX_TONE_NUM_134,
     BYLE_KWS_IDEX_TONE_NUM_135,
     BYLE_KWS_IDEX_TONE_NUM_136,
     BYLE_KWS_IDEX_TONE_NUM_137,
     BYLE_KWS_IDEX_TONE_NUM_138,
     BYLE_KWS_IDEX_TONE_NUM_139,
     BYLE_KWS_IDEX_TONE_NUM_140,
     BYLE_KWS_IDEX_TONE_NUM_141,
     BYLE_KWS_IDEX_TONE_NUM_142,
     BYLE_KWS_IDEX_TONE_NUM_143,
     BYLE_KWS_IDEX_TONE_NUM_144,
     BYLE_KWS_IDEX_TONE_NUM_145,
     BYLE_KWS_IDEX_TONE_NUM_146,
     BYLE_KWS_IDEX_TONE_NUM_147,
     BYLE_KWS_IDEX_TONE_NUM_148,
     BYLE_KWS_IDEX_TONE_NUM_149,
     BYLE_KWS_IDEX_TONE_NUM_150,
     BYLE_KWS_IDEX_TONE_NUM_151,
     BYLE_KWS_IDEX_TONE_NUM_152,
     BYLE_KWS_IDEX_TONE_NUM_153,
     BYLE_KWS_IDEX_TONE_NUM_154,
     BYLE_KWS_IDEX_TONE_NUM_155,
     BYLE_KWS_IDEX_TONE_NUM_156,
     BYLE_KWS_IDEX_TONE_NUM_157,
     BYLE_KWS_IDEX_TONE_NUM_158,
     BYLE_KWS_IDEX_TONE_NUM_159,
     BYLE_KWS_IDEX_TONE_NUM_160,
     BYLE_KWS_IDEX_TONE_NUM_161,
     BYLE_KWS_IDEX_TONE_NUM_162,
     BYLE_KWS_IDEX_TONE_NUM_163,
     BYLE_KWS_IDEX_TONE_NUM_164,
     BYLE_KWS_IDEX_TONE_NUM_165,
     BYLE_KWS_IDEX_TONE_NUM_166,
     BYLE_KWS_IDEX_TONE_NUM_167,
     BYLE_KWS_IDEX_TONE_NUM_168,
     BYLE_KWS_IDEX_TONE_NUM_169,
     BYLE_KWS_IDEX_TONE_NUM_170,
     BYLE_KWS_IDEX_TONE_NUM_171,

     BYLE_KWS_IDEX_TONE_NONE
};
#ifndef SDFILE_RES_ROOT_PATH
#define SDFILE_MOUNT_PATH     	"mnt/sdfile"
#define SDFILE_RES_ROOT_PATH       	SDFILE_MOUNT_PATH"/res/"  //资源文件分区
#endif

static const char *const Byle_kws_tone_index[] = {
    [BYLE_KWS_IDEX_TONE_NUM_101] = SDFILE_RES_ROOT_PATH"tone/101.*",
    [BYLE_KWS_IDEX_TONE_NUM_102] = SDFILE_RES_ROOT_PATH"tone/102.*",
    [BYLE_KWS_IDEX_TONE_NUM_103] = SDFILE_RES_ROOT_PATH"tone/103.*",
    [BYLE_KWS_IDEX_TONE_NUM_104] = SDFILE_RES_ROOT_PATH"tone/104.*",
    [BYLE_KWS_IDEX_TONE_NUM_105] = SDFILE_RES_ROOT_PATH"tone/105.*",
    [BYLE_KWS_IDEX_TONE_NUM_106] = SDFILE_RES_ROOT_PATH"tone/106.*",
    [BYLE_KWS_IDEX_TONE_NUM_107] = SDFILE_RES_ROOT_PATH"tone/107.*",
    [BYLE_KWS_IDEX_TONE_NUM_108] = SDFILE_RES_ROOT_PATH"tone/108.*",
    [BYLE_KWS_IDEX_TONE_NUM_109] = SDFILE_RES_ROOT_PATH"tone/109.*",
    [BYLE_KWS_IDEX_TONE_NUM_110] = SDFILE_RES_ROOT_PATH"tone/110.*",
    [BYLE_KWS_IDEX_TONE_NUM_111] = SDFILE_RES_ROOT_PATH"tone/111.*",
    [BYLE_KWS_IDEX_TONE_NUM_112] = SDFILE_RES_ROOT_PATH"tone/112.*",
    [BYLE_KWS_IDEX_TONE_NUM_113] = SDFILE_RES_ROOT_PATH"tone/113.*",
    [BYLE_KWS_IDEX_TONE_NUM_114] = SDFILE_RES_ROOT_PATH"tone/114.*",
    [BYLE_KWS_IDEX_TONE_NUM_115] = SDFILE_RES_ROOT_PATH"tone/115.*",
    [BYLE_KWS_IDEX_TONE_NUM_116] = SDFILE_RES_ROOT_PATH"tone/116.*",
    [BYLE_KWS_IDEX_TONE_NUM_117] = SDFILE_RES_ROOT_PATH"tone/117.*",
    [BYLE_KWS_IDEX_TONE_NUM_118] = SDFILE_RES_ROOT_PATH"tone/118.*",
    [BYLE_KWS_IDEX_TONE_NUM_119] = SDFILE_RES_ROOT_PATH"tone/119.*",
    [BYLE_KWS_IDEX_TONE_NUM_120] = SDFILE_RES_ROOT_PATH"tone/120.*",
    [BYLE_KWS_IDEX_TONE_NUM_121] = SDFILE_RES_ROOT_PATH"tone/121.*",
    [BYLE_KWS_IDEX_TONE_NUM_122] = SDFILE_RES_ROOT_PATH"tone/122.*",
    [BYLE_KWS_IDEX_TONE_NUM_123] = SDFILE_RES_ROOT_PATH"tone/123.*",
    [BYLE_KWS_IDEX_TONE_NUM_124] = SDFILE_RES_ROOT_PATH"tone/124.*",
    [BYLE_KWS_IDEX_TONE_NUM_125] = SDFILE_RES_ROOT_PATH"tone/125.*",
    [BYLE_KWS_IDEX_TONE_NUM_126] = SDFILE_RES_ROOT_PATH"tone/126.*",
    [BYLE_KWS_IDEX_TONE_NUM_127] = SDFILE_RES_ROOT_PATH"tone/127.*",
    [BYLE_KWS_IDEX_TONE_NUM_128] = SDFILE_RES_ROOT_PATH"tone/128.*",
    [BYLE_KWS_IDEX_TONE_NUM_129] = SDFILE_RES_ROOT_PATH"tone/129.*",
    [BYLE_KWS_IDEX_TONE_NUM_130] = SDFILE_RES_ROOT_PATH"tone/130.*",
    [BYLE_KWS_IDEX_TONE_NUM_131] = SDFILE_RES_ROOT_PATH"tone/131.*",
    [BYLE_KWS_IDEX_TONE_NUM_132] = SDFILE_RES_ROOT_PATH"tone/132.*",
    [BYLE_KWS_IDEX_TONE_NUM_133] = SDFILE_RES_ROOT_PATH"tone/133.*",
    [BYLE_KWS_IDEX_TONE_NUM_134] = SDFILE_RES_ROOT_PATH"tone/134.*",
    [BYLE_KWS_IDEX_TONE_NUM_135] = SDFILE_RES_ROOT_PATH"tone/135.*",
    [BYLE_KWS_IDEX_TONE_NUM_136] = SDFILE_RES_ROOT_PATH"tone/136.*",
    [BYLE_KWS_IDEX_TONE_NUM_137] = SDFILE_RES_ROOT_PATH"tone/137.*",
    [BYLE_KWS_IDEX_TONE_NUM_138] = SDFILE_RES_ROOT_PATH"tone/138.*",
    [BYLE_KWS_IDEX_TONE_NUM_139] = SDFILE_RES_ROOT_PATH"tone/139.*",
    [BYLE_KWS_IDEX_TONE_NUM_140] = SDFILE_RES_ROOT_PATH"tone/140.*",
    [BYLE_KWS_IDEX_TONE_NUM_141] = SDFILE_RES_ROOT_PATH"tone/141.*",
    [BYLE_KWS_IDEX_TONE_NUM_142] = SDFILE_RES_ROOT_PATH"tone/142.*",
    [BYLE_KWS_IDEX_TONE_NUM_143] = SDFILE_RES_ROOT_PATH"tone/143.*",
    [BYLE_KWS_IDEX_TONE_NUM_144] = SDFILE_RES_ROOT_PATH"tone/144.*",
    [BYLE_KWS_IDEX_TONE_NUM_145] = SDFILE_RES_ROOT_PATH"tone/145.*",
    [BYLE_KWS_IDEX_TONE_NUM_146] = SDFILE_RES_ROOT_PATH"tone/146.*",
    [BYLE_KWS_IDEX_TONE_NUM_147] = SDFILE_RES_ROOT_PATH"tone/147.*",
    [BYLE_KWS_IDEX_TONE_NUM_148] = SDFILE_RES_ROOT_PATH"tone/148.*",
    [BYLE_KWS_IDEX_TONE_NUM_149] = SDFILE_RES_ROOT_PATH"tone/149.*",
    [BYLE_KWS_IDEX_TONE_NUM_150] = SDFILE_RES_ROOT_PATH"tone/150.*",
    [BYLE_KWS_IDEX_TONE_NUM_151] = SDFILE_RES_ROOT_PATH"tone/151.*",
    [BYLE_KWS_IDEX_TONE_NUM_152] = SDFILE_RES_ROOT_PATH"tone/152.*",
    [BYLE_KWS_IDEX_TONE_NUM_153] = SDFILE_RES_ROOT_PATH"tone/153.*",
    [BYLE_KWS_IDEX_TONE_NUM_154] = SDFILE_RES_ROOT_PATH"tone/154.*",
    [BYLE_KWS_IDEX_TONE_NUM_155] = SDFILE_RES_ROOT_PATH"tone/155.*",
    [BYLE_KWS_IDEX_TONE_NUM_156] = SDFILE_RES_ROOT_PATH"tone/156.*",
    [BYLE_KWS_IDEX_TONE_NUM_157] = SDFILE_RES_ROOT_PATH"tone/157.*",
    [BYLE_KWS_IDEX_TONE_NUM_158] = SDFILE_RES_ROOT_PATH"tone/158.*",
    [BYLE_KWS_IDEX_TONE_NUM_159] = SDFILE_RES_ROOT_PATH"tone/159.*",
    [BYLE_KWS_IDEX_TONE_NUM_160] = SDFILE_RES_ROOT_PATH"tone/160.*",
    [BYLE_KWS_IDEX_TONE_NUM_161] = SDFILE_RES_ROOT_PATH"tone/161.*",
    [BYLE_KWS_IDEX_TONE_NUM_162] = SDFILE_RES_ROOT_PATH"tone/162.*",
    [BYLE_KWS_IDEX_TONE_NUM_163] = SDFILE_RES_ROOT_PATH"tone/163.*",
    [BYLE_KWS_IDEX_TONE_NUM_164] = SDFILE_RES_ROOT_PATH"tone/164.*",
    [BYLE_KWS_IDEX_TONE_NUM_165] = SDFILE_RES_ROOT_PATH"tone/165.*",
    [BYLE_KWS_IDEX_TONE_NUM_166] = SDFILE_RES_ROOT_PATH"tone/166.*",
    [BYLE_KWS_IDEX_TONE_NUM_167] = SDFILE_RES_ROOT_PATH"tone/167.*",
    [BYLE_KWS_IDEX_TONE_NUM_168] = SDFILE_RES_ROOT_PATH"tone/168.*",
    [BYLE_KWS_IDEX_TONE_NUM_169] = SDFILE_RES_ROOT_PATH"tone/169.*",
    [BYLE_KWS_IDEX_TONE_NUM_170] = SDFILE_RES_ROOT_PATH"tone/170.*",
    [BYLE_KWS_IDEX_TONE_NUM_171] = SDFILE_RES_ROOT_PATH"tone/171.*",
};

#ifdef BYLE_UATR_ENABLE
#define TONE_CMD_TABLE
static const unsigned char tone_cmd_table[]={
101,
102,
103,
104,
105,
106,
107,
108,
109,
110,
111,
112,
113,
114,
115,
116,
117,
118,
119,
120,
121,
122,
123,
124,
125,
126,
127,
128,
129,
130,
131,
132,
133,
134,
135,
136,
137,
138,
139,
140,
141,
142,
143,
144,
145,
146,
147,
148,
149,
150,
151,
152,
153,
154,
155,
156,
157,
158,
159,
160,
161,
162,
163,
164,
165,
166,
167,
168,
169,
170,
171,
};

#endif
#define KEY_NULL1 KEY_NULL-1
static const u16 Byle_kws_msg_table[]=

		{

				  KEY_NULL,//	 eCMD_wakeup_uni,//0小红
				  MSG_LED_USB_NIGHT_ON,//default_open=开灯@好的
				  MSG_LED_OFF,//default_close=关灯@好的
				  MSG_LED_VOICE_BRIGHT_UP,//	brightthelight=亮一点@好的
				  MSG_LED_VOICE_BRIGHT_DOWM ,//  dimthelight=暗一点@好的
				  MSG_LED_COLOR_DISP_MODE_SEL_NO_WY,// changecolor=变颜色@好的
				  MSG_LED_SENOR_MODE,//   musicmode=音乐模式@好的
				  MSG_LED_COLOR_FULL_CHANGE,// ColorfulMode=七彩模式@好的

      MSG_LED_WHITE,//  eCMD_white,
      MSG_LED_REG,// eCMD_red,
      MSG_LED_ORANGE,// eCMD_orange,      //BZ
      MSG_LED_YELLOW,// eCMD_yellow,
      MSG_LED_GREEG,//  eCMD_green,
      MSG_LED_cyan,//  eCMD_cyan,
      MSG_LED_BLUE,// eCMD_blue,
      MSG_LED_PURPLE,// eCMD_purple,


		};

static const u16 music_led_msg_table[NLU_CONTENT_SIZE]=
	{

              KEY_NULL,//    eCMD_wakeup_uni,//0小红
              MSG_LED_USB_NIGHT_ON,//default_open=开灯@好的
              MSG_LED_OFF,//default_close=关灯@好的
              MSG_LED_VOICE_BRIGHT_UP,//	brightthelight=亮一点@好的
              MSG_LED_VOICE_BRIGHT_DOWM	,//  dimthelight=暗一点@好的
              MSG_LED_COLOR_DISP_MODE_SEL_NO_WY,// changecolor=变颜色@好的
              MSG_LED_SENOR_MODE,//   musicmode=音乐模式@好的
              MSG_LED_COLOR_FULL_CHANGE,// ColorfulMode=七彩模式@好的

                    MSG_LED_WHITE,//  eCMD_white,
      MSG_LED_REG,// eCMD_red,
      MSG_LED_ORANGE,// eCMD_orange,      //BZ
      MSG_LED_YELLOW,// eCMD_yellow,
      MSG_LED_GREEG,//  eCMD_green,
      MSG_LED_cyan,//  eCMD_cyan,
      MSG_LED_BLUE,// eCMD_blue,
      MSG_LED_PURPLE,// eCMD_purple,

	};

static const u16 music_led_wyrgb_msg_table[NLU_CONTENT_SIZE]=
	{

              KEY_NULL,//    eCMD_wakeup_uni,//0小红
              MSG_LED_USB_NIGHT_ON,//default_open=开灯@好的
              MSG_LED_OFF,//default_close=关灯@好的
              MSG_LED_VOICE_BRIGHT_UP,//	brightthelight=亮一点@好的
              MSG_LED_VOICE_BRIGHT_DOWM	,//  dimthelight=暗一点@好的
              MSG_LED_COLOR_SEL_WITH_WY,// changecolor=变颜色@好的
              MSG_LED_SENOR_MODE,//   musicmode=音乐模式@好的
              MSG_LED_COLOR_FULL_CHANGE,// ColorfulMode=七彩模式@好的

      MSG_LED_WHITE,//  eCMD_white,
      MSG_LED_REG,// eCMD_red,
      MSG_LED_ORANGE,// eCMD_orange,      //BZ
      MSG_LED_YELLOW,// eCMD_yellow,
      MSG_LED_GREEG,//  eCMD_green,
      MSG_LED_cyan,//  eCMD_cyan,
      MSG_LED_BLUE,// eCMD_blue,
      MSG_LED_PURPLE,// eCMD_purple,


	};
static const u16 music_led_wrgb_msg_table[NLU_CONTENT_SIZE]=
	{

              KEY_NULL,//    eCMD_wakeup_uni,//0小红
              MSG_LED_USB_NIGHT_ON,//default_open=开灯@好的
              MSG_LED_OFF,//default_close=关灯@好的
              MSG_LED_VOICE_BRIGHT_UP,//	brightthelight=亮一点@好的
              MSG_LED_VOICE_BRIGHT_DOWM	,//  dimthelight=暗一点@好的
              MSG_LED_COLOR_SEL_WITH_W,// changecolor=变颜色@好的
              MSG_LED_SENOR_MODE,//   musicmode=音乐模式@好的
              MSG_LED_COLOR_FULL_CHANGE,// ColorfulMode=七彩模式@好的

      MSG_LED_WHITE,//  eCMD_white,
      MSG_LED_REG,// eCMD_red,
      MSG_LED_ORANGE,// eCMD_orange,      //BZ
      MSG_LED_YELLOW,// eCMD_yellow,
      MSG_LED_GREEG,//  eCMD_green,
      MSG_LED_cyan,//  eCMD_cyan,
      MSG_LED_BLUE,// eCMD_blue,
      MSG_LED_PURPLE,// eCMD_purple,


	};

static const u16 music_led_wy_msg_table[NLU_CONTENT_SIZE]=
	{

              KEY_NULL,//    eCMD_wakeup_uni,//0小红
              MSG_LED_USB_NIGHT_ON,//default_open=开灯@好的
              MSG_LED_OFF,//default_close=关灯@好的
              MSG_LED_VOICE_BRIGHT_UP,//	brightthelight=亮一点@好的
              MSG_LED_VOICE_BRIGHT_DOWM	,//  dimthelight=暗一点@好的
              MSG_LED_VOICE_COLOR_TEMP,// changecolor=变颜色@好的
              KEY_NULL,//   musicmode=音乐模式@好的
              KEY_NULL,// ColorfulMode=七彩模式@好的

	};

static const u16 music_led_w_msg_table[NLU_CONTENT_SIZE]=
	{

              KEY_NULL,//    eCMD_wakeup_uni,//0小红
              MSG_LED_USB_NIGHT_ON,//default_open=开灯@好的
              MSG_LED_OFF,//default_close=关灯@好的
              MSG_LED_VOICE_BRIGHT_UP,//	brightthelight=亮一点@好的
              MSG_LED_VOICE_BRIGHT_DOWM	,//  dimthelight=暗一点@好的
              KEY_NULL,// changecolor=变颜色@好的
              KEY_NULL,//   musicmode=音乐模式@好的
              KEY_NULL,// ColorfulMode=七彩模式@好的

	};
#endif
