/**************************************************************************
 * Copyright (C) 2012-2021  Unisound
 *
 * DO NOT MODIFY.
 *
 * This file was generated by res_build_tool.py
 *
 **************************************************************************/
#ifndef INC_TONE_RESOURCE_H_
#define INC_TONE_RESOURCE_H_

#include <stdint.h>
typedef struct tone_map_s {
	uint16_t idx;
	uint16_t name;
} tone_map_t;

enum {
    IDEX_TONE_NUM_0,
    IDEX_TONE_NUM_1,
    IDEX_TONE_NUM_2,
    IDEX_TONE_NUM_3,
    IDEX_TONE_NUM_4,
    IDEX_TONE_NUM_5,
    IDEX_TONE_NUM_6,
    IDEX_TONE_NUM_7,
    IDEX_TONE_NUM_8,
    IDEX_TONE_NUM_9,
    IDEX_TONE_NUM_101,
    IDEX_TONE_NUM_102,

    IDEX_TONE_NONE = 0xFF
};

static const char *const tone_index[] = {
    [IDEX_TONE_NUM_0] = SDFILE_RES_ROOT_PATH"tone/0.*",
    [IDEX_TONE_NUM_1] = SDFILE_RES_ROOT_PATH"tone/1.*",
    [IDEX_TONE_NUM_2] = SDFILE_RES_ROOT_PATH"tone/2.*",
    [IDEX_TONE_NUM_3] = SDFILE_RES_ROOT_PATH"tone/3.*",
    [IDEX_TONE_NUM_4] = SDFILE_RES_ROOT_PATH"tone/4.*",
    [IDEX_TONE_NUM_5] = SDFILE_RES_ROOT_PATH"tone/5.*",
    [IDEX_TONE_NUM_6] = SDFILE_RES_ROOT_PATH"tone/6.*",
    [IDEX_TONE_NUM_7] = SDFILE_RES_ROOT_PATH"tone/7.*",
    [IDEX_TONE_NUM_8] = SDFILE_RES_ROOT_PATH"tone/8.*",
    [IDEX_TONE_NUM_9] = SDFILE_RES_ROOT_PATH"tone/9.*",
    [IDEX_TONE_NUM_101] = SDFILE_RES_ROOT_PATH"tone/101.*",
    [IDEX_TONE_NUM_102] = SDFILE_RES_ROOT_PATH"tone/102.*",
};

static const tone_map_t tone_mapping[] = {
    {IDEX_TONE_NUM_0, 0},
    {IDEX_TONE_NUM_1, 1},
    {IDEX_TONE_NUM_2, 2},
    {IDEX_TONE_NUM_3, 3},
    {IDEX_TONE_NUM_4, 4},
    {IDEX_TONE_NUM_5, 5},
    {IDEX_TONE_NUM_6, 6},
    {IDEX_TONE_NUM_7, 7},
    {IDEX_TONE_NUM_8, 8},
    {IDEX_TONE_NUM_9, 9},
    {IDEX_TONE_NUM_101, 101},
    {IDEX_TONE_NUM_102, 102},
};

#endif
